replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

deploymentAnnotations: {}
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

containerPort: 80
command: []
args: []
env: []
envFrom: []

service:
  type: ClusterIP
  port: 80
  annotations: {}

sloth:
  enabled: false
  annotations: {}
  service: ""
  labels: {}
  slos: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: http
  hostnames: []
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

resources: {}

startupProbe: {}
livenessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 5
  failureThreshold: 2

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: null
  behavior: {}

pdb:
  enabled: false
  minAvailable: null
  maxUnavailable: 1

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

terminationGracePeriodSeconds: 30

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
